### ISSUE TITLE
Register on https://joss.theoj.org/ and Write the orcid

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Intern-Ids#1]
Please create an account on https://joss.theoj.org/ and write your `orcid` as a comment on this ticket. After you register you will receive the `orcid` checkout the email id you created the account w/.

**Comment by nightwarriorftw** [comment]
```Orchid ID```
https://orcid.org/0000-0002-0087-5347

**Comment by KevinChittilapilly** [comment]
#Orchid ID
https://orcid.org/0000-0001-6268-0601

**Comment by KevinChittilapilly** [comment]
#orcid1
https://orcid.org/0000-0001-6268-0601

**Comment by KevinChittilapilly** [comment]
#17 
https://orcid.org/0000-0001-6268-0601

**Comment by KevinChittilapilly** [comment]
https://orcid.org/0000-0001-6268-0601

**Comment by Aashi15bansal** [comment]
Ashita Bansal
https://orcid.org/0000-0001-9649-1809

**Comment by kumar-hardik** [comment]
Hardik Kumar
https://orcid.org/0000-0002-1092-611X

**Comment by bymayanksingh** [comment]
Mayank Singh
https://orcid.org/0000-0003-4108-424X

**Comment by NiharikaMessi** [comment]
Niharika Vadlamudi

https://orcid.org/0000-0001-6596-428X
