### ISSUE TITLE
Write orcids

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Intern-Ids#12]
https://accounts.osf.io/login?service=https%3A%2F%2Fosf.io%2Flogin%2F%3Fnext%3Dhttps%253A%252F%252Fosf.io%252Fpreprints%252Fsocarxiv%252Fsubmit

**Comment by nightwarriorftw** [comment]
0000-0002-0087-5347

**Comment by KevinChittilapilly** [comment]
0000-0001-6268-0601

**Comment by bymayanksingh** [comment]
0000-0003-4108-424X

**Comment by Aashi15bansal** [comment]
0000-0001-9649-1809

**Comment by shah-aman** [comment]
0000-0002-9739-360X

**Comment by NiharikaMessi** [comment]
Niharika Vadlamudi : 
0000-0001-6596-428X

**Comment by tapaswenipathak** [comment]
@ucalyptus

**Comment by ucalyptus** [comment]
Sayantan Dasl
0000-0002-3377-0293
