### ISSUE TITLE
Nature manuscripts submit 

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Intern-Ids#2]
https://www.nature.com/hgv/
https://www.nature.com/natecolevol/

Write username

**Comment by tapaswenipathak** [comment]
@code-monk08 @kumar-hardik  @nightwarrior-xxx @NiharikaMessi

**Comment by nightwarriorftw** [comment]
amanv1999@gmail.com

**Comment by NiharikaMessi** [comment]
niharika11988@gmai.com

**Comment by tapaswenipathak** [comment]
👋 ping @code-monk08 @kumar-hardik

**Comment by bymayanksingh** [comment]
mayank.singh081997@gmail.com

**Comment by ucalyptus** [comment]
sayantandas30011998@gmail.com

**Comment by sujay0399** [comment]
kumarsujay456@gmail.com

**Comment by kumar-hardik** [comment]
hardik.kumar2@gmail.com
