### ISSUE TITLE
Write username on the ticket

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Intern-Ids#4]
http://www.scholarpedia.org/w/index.php?title=Special:UserLogin&type=signup

**Comment by shah-aman** [comment]
http://www.scholarpedia.org/article/User:Aman_shah

**Comment by Aashi15bansal** [comment]
http://www.scholarpedia.org/article/User:Ashita_Bansal

**Comment by NiharikaMessi** [comment]
http://www.scholarpedia.org/article/User:Niharika_Vadlamudi

**Comment by bhaskartalla** [comment]
http://www.scholarpedia.org/article/User:Bhaskar_talla_balakisan

**Comment by tapaswenipathak** [comment]
@ucalyptus

**Comment by ucalyptus** [comment]
http://www.scholarpedia.org/article/User:Sayantan_Das
