### ISSUE TITLE
Write the username on the ticket

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Intern-Ids#5]
https://authors.repec.org/

**Comment by charusinha** [comment]
User ID for Repec - charu2mail@gmail.com
Short id for Repec- psi834

**Comment by bymayanksingh** [comment]
User ID: mayank.singh081997@gmail.com
Short-ID is psi835

**Comment by shah-aman** [comment]
User ID : aman.shah008@gmail.com
Short ID : psh1043
